### ISSUE TITLE
can't list packages from feeds via Account feed

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/website#623] opened 2019-05-26 07:41 UTC
hi, i still can list the nuget package via Account feed.

i repro steps as follow.
1. run build on my private Appveyor Server(Version: 7.0.2150 Community Edition)
![log](http://images.sdgxgz.com/appveyor_log.png "log")
2. list packages in vs.
![vs](http://images.sdgxgz.com/appveyor_vs.png "vs")
Longbow.Cache (v2.2.10) work well. but miss Longbow (v2.2.9)
3. list packages in command window.
![cmd](http://images.sdgxgz.com/appveyor_cmd.png "cmd")
it's same result with vs. but with -allversion was correct.
4. check sqlite database on server.
![db2](http://images.sdgxgz.com/appveyor_db2.png "db2")
![db1](http://images.sdgxgz.com/appveyor_db1.png "db1")
it looks normal.
why can't list Longbow.dll (v2.2.9)?

**Comment by FeodorFitsner** [comment] 2019-05-26 15:59
Could you drop the entire contents of `NuGetPackages` table please?

**Comment by ArgoZhang** [comment] 2019-05-27 00:35
above screenshot is entire contents of NugetPackages. the old data had been deleted yesterday

**Comment by ArgoZhang** [comment] 2019-05-27 01:29
@FeodorFitsner hi, i upload the entire database zip package. you can click [here](http://images.sdgxgz.com/appveyor-server.db.zip) download it.
because i run appveyor.yml script again. so now miss Longbow.dll & Longbow.Cache.dll.
i guess it's a bug. always miss the previous packages.
![cmd](http://images.sdgxgz.com/appveyor_cmd2.png "")

**Comment by FeodorFitsner** [comment] 2019-05-27 01:33
Yeah, looks like a bug. Will be working on a fix - thanks for sharing additional info.

**Comment by ArgoZhang** [comment] 2019-05-27 01:36
my pleasure. please let me know when release the new version.

**Comment by ArgoZhang** [comment] 2019-05-27 01:38
btw: I think that appveyor website should provider a page for query all packages in Account feed link www.nuget.org home query page.

**Comment by FeodorFitsner** [comment] 2019-05-27 19:08
I'm trying to reproduce the behavior with missing packages in the feed, but having some difficulties.

...If you completely delete contents of both `NuGetFeedPackages` and `NuGetPackages` tables and build again can you see all the packages without `-allversions` option?

**Comment by FeodorFitsner** [comment] 2019-05-27 19:19
I mean, would be great to have a repro from scratch.

**Comment by ArgoZhang** [comment] 2019-05-28 00:35
fine. I will try later. wake up now.

**Comment by ArgoZhang** [comment] 2019-05-28 01:11
@FeodorFitsner OMG! i can't repro too! i don't know what happened.

**Comment by FeodorFitsner** [comment] 2019-05-28 01:14
Thanks for checking. Let's close this issue for now? Next time you encounter this misbehavior try to catch the steps to reproduce (if possible).

**Comment by ArgoZhang** [comment] 2019-05-28 01:15
ok. thanks for you help.

**Comment by ArgoZhang** [comment] 2019-05-30 01:05
```
Z:\src\Longbow\BootstrapAdmin\Bootstrap.Admin>nuget list -source https://app.sdgxgz.com/nuget/appveyor-kd558oo19384 -allversions
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Please provide credentials for: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
UserName: argo@163.com
Password: **********
Bootstrap.Security 1.3.0
Bootstrap.Security.DataAccess 2.2.4
Bootstrap.Security.Mvc 2.2.6
Longbow 2.2.9
Longbow.Cache 2.2.10
Longbow.ComponentModel 1.3.0
Longbow.Configuration 2.2.2
Longbow.Data 2.3.2
Longbow.IO 1.0.0
Longbow.Logging 2.2.6
Longbow.Net 2.2.5
Longbow.Security.Cryptography 1.3.0
Longbow.ServiceModel 1.2.0
Longbow.Tasks 1.3.0
Longbow.Web 2.2.11
PetaPoco.Extensions 1.0.5
TestForAppveyor 1.0.2
TestForAppveyor 1.0.1
TestForAppveyor 1.0.0

Z:\src\Longbow\BootstrapAdmin\Bootstrap.Admin>nuget list -source https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Please provide credentials for: https://app.sdgxgz.com/nuget/appveyor-kd558oo19384
UserName: argo@163.com
Password: **********
TestForAppveyor 1.0.2
Z:\src\Longbow\BootstrapAdmin\Bootstrap.Admin>
```
again! only the previous artifact on the list.

**Comment by FeodorFitsner** [comment] 2019-05-30 01:14
What's the contents of `NuGetPackages` table?

**Comment by ArgoZhang** [comment] 2019-05-30 01:38
same with the command result without -allversion. only list the one TestForAppveyor 1.0.2

**Comment by FeodorFitsner** [comment] 2019-05-30 01:39
I mean could you share the contents of `NuGetPackages` database table?

**Comment by ArgoZhang** [comment] 2019-05-30 01:42
ok. click [here](http://images.sdgxgz.com/appveyor_db_0530.zip) download the db zip file.

**Comment by FeodorFitsner** [comment] 2019-05-30 01:53
Got it, thanks.

**Comment by FeodorFitsner** [comment] 2019-05-30 01:56
So, basically, you are publishing NuGet packages with the same versions over and over again. This might be a key to the issue. Will try to do a repro.

**Comment by ArgoZhang** [comment] 2019-05-30 02:07
you are right. I notice that it works if the version changed. but same version is reasonable. now I try do not generate artifacts when same version. but can not set condition in artifacts phase.

**Comment by FeodorFitsner** [comment] 2019-05-30 20:58
We've fixed this bug. Please install the latest https://www.appveyor.com/downloads/appveyor-server/7.0/windows/appveyor-server-7.0.2166-x64.msi (it's not signed yet)

Remove contents of `NuGetFeedPackages` and `NuGetPackages` tables first.

**Comment by ArgoZhang** [comment] 2019-05-31 00:53
works. thanks so much. :)

**Closed** 2019-05-31 01:04 UTC
